### ISSUE TITLE
Idea for a new feature - No generate Chessboard when unbreakable blocks

### ISSUE THREAD

**Issue by MrAmericanMike** [MaartenKok8/MineChess#5]
I just have a small question / feature request.
The idea is to prevent chessboards from generating, the player placed ones (either on X dimensions) or when unbreakable blocks are present.
The "problem" is that in a ModPack I'm helping to develop, players use the Chessboard to break an entry to the final boss.

Thanks a lot, sorry if it goes posted on another category, I never sure if things like this goes here or under "Pull requests" on Github.

(As a reference, for example, the blocks I'm talking about are in the Aether II Mod inside the dungeon)

**Comment by MineMaarten** [comment]
No, even though it's labeled as 'issues' suggestions also need to go here ;). Pull requests are when people actually submit code to be merged into the mod. That isn't the case in this case.

Anyway, a new build is on curseforge ;)

**Comment by MrAmericanMike** [comment]
Wow that was fast. Thanks a lot man, did some tests on that dungeon I told you and it works like a charm.
Really appreciate. Thanks.
